POST localhost:8080/api/auth/naver
Content-Type: application/json

{
  "authorizationCode": "4Ap9FqtOkYBzzRa2J8",
  "state": null
}


###
POST localhost:8080/api/mail/send
Content-Type: application/json

{
  "email": "xodnjs8287@naver.com"
}